### ISSUE TITLE
dashboard template with existing uid

### ISSUE THREAD

**Issue by bee-mois** [hiveeyes/ds18b20-datalogger#11]
`ds18b20-datalogger make-dashboard > dashboard.json`
is producing a grafana dashboard template.
but it is containing a _fixed_ uid of an _existing_ dashboard.
that uid should be a pseudo-random string dynamically created when creating the template.
for details and screenshot see the [forum post](https://community.hiveeyes.org/t/ds18b20-datenlogger-mit-raspberry-pi-und-grafana/5321/10).

**Comment by amotl** [comment]
That makes sense. Thanks. What happens if you just omit the uid attribute? Will Grafana accompany us aiming for [DWIM](https://en.wikipedia.org/wiki/DWIM), and will just assign a new uid on its own behalf?

Can you try to apply that approach by just deleting the attribute from the JSON before uploading?

**Comment by bee-mois** [comment]
indeed. pasting the .json without the uid line 
`2038:   "uid": "ldkjfg",`
solves the issue. 
no more warning, no more override button. 
new uid created by grafana.

**Comment by amotl** [comment]
Thanks for confirming. Fixed with 20be04a56b6 on behalf of GH-14.

**Comment by bee-mois** [comment]
thanx.
